app:
  name: go-wire
  mode: debug
  port: 8080
  limit: 1
  burst: 5
  client_id: "tC0ND8ar26Jk9L5b"
allow_origins:
  - "http://192.168.3.42:8000"
redis:
  default:
    addr: 127.0.0.1:6379
    password: ""
    db: 0
log:
  director: log
  level: info
  maxAge: 7
  maxSize: 100
  maxBackups: 10
  format: console